### ISSUE TITLE
attempt to call method 'cluster' (a nil value)

### ISSUE THREAD

**Issue by SeauWong** [steve0511/resty-redis-cluster#53]
2019/11/27 16:34:51 [error] 15214#0: *1 lua entry thread aborted: runtime error: /usr/local/wongcu/openresty/lualib/rediscluster.lua:127: attempt to call method 'cluster' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/wongcu/openresty/lualib/rediscluster.lua: in function 'try_hosts_slots'
	/usr/local/wongcu/openresty/lualib/rediscluster.lua:160: in function 'fetch_slots'
	/usr/local/wongcu/openresty/lualib/rediscluster.lua:191: in function 'init_slots'
	/usr/local/wongcu/openresty/lualib/rediscluster.lua:207: in function 'new'
	content_by_lua(nginx.conf:52):2: in function <content_by_lua(nginx.conf:52):1>, client: 127.0.0.1, server: , request: "GET /lua_content HTTP/1.1", host: "localhost:8899"

**Comment by SeauWong** [comment]
解决了
vi /usr/local/openresty/lualib/resty/redis.lua
在 command={...}命令列表里加入"cluster"

作者能否特别说明一下，这个还是有点坑的

**Comment by clpgr** [comment]
@SeauWong 
That's because you are using an older version of lua-resty-redis. In older versions, you need to call add_commands to add any command that is not in the list. 
You don't need to do this in newer versions since any command not in common_cmds list is automatically added to the module the first time it's used.

**Comment by SeauWong** [comment]
@clpgr  it works to me, thank you
